version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - DomPilipu
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.28
    - 14.14.32
  - dependency-name: typescript
    versions:
    - 4.2.2
